### ISSUE TITLE
Support removed for rootless containers?

### ISSUE THREAD

**Issue by gmarcy** [openshift/assisted-service#4819]
I can no longer run Assisted-Install using a rootless podman pod.
This has never been a problem before.

as myself
```
$ podman run --rm -ti quay.io/centos7/postgresql-12-centos7:latest bash
bash-4.2$ cgroup-limits 
Warning: Can't detect cpu quota from cgroups
Warning: Can't detect cpuset size from cgroups
Traceback (most recent call last):
  File "/usr/bin/cgroup-limits", line 143, in <module>
    "NUMBER_OF_CORES": get_number_of_cores()
  File "/usr/bin/cgroup-limits", line 76, in get_number_of_cores
    return min([l for l in limits if l])
ValueError: min() arg is an empty sequence
bash-4.2$ id  
uid=26(postgres) gid=26(postgres) groups=26(postgres),0(root)
bash-4.2$ 
```
as root
```
$ sudo podman run --rm -ti quay.io/centos7/postgresql-12-centos7:latest bash
bash-4.2$ cgroup-limits 
NO_MEMORY_LIMIT=true
MAX_MEMORY_LIMIT_IN_BYTES=9223372036854775807
MEMORY_LIMIT_IN_BYTES=9223372036854775807
NUMBER_OF_CORES=20
bash-4.2$ 
```

Was this an accidental or intentional change in behavior?

**Comment by vrutkovs** [comment]
Submitted to Jira as https://issues.redhat.com/browse/MGMT-13209
